# Generated by Django 4.2.8 on 2024-03-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='PresentacionesTXT/')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
    ]
