version: '3'

services:
  web:
    build: ./django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'db_name'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
